blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('singlepageblog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

singlepageblog/urls.py
from django.urls import path

from . import views

app_name = 'singlepageblog'

urlpatterns = [
    path('', views.index, name='index'),
    path('tag/<str:name>', views.blog_tag, name='tagBlog'),
    path('<slug:slug>/', views.blog_detail, name='blogDetail')
]

singlepageblog/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.urls import reverse

# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("singlepageblog:tagBlog", kwargs={"name": self.name})


class Blog(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, default=None)
    date = models.DateTimeField()
    image = models.ImageField(
        upload_to='blog/', default='default.jpg', blank=True, null=True)
    content = models.TextField(default=None)
    draft = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("singlepageblog:blogDetail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ["-date"]
        verbose_name = "My Blog"
        verbose_name = "My Blogs"


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Blog.objects.filter(slug=slug).order_by("-id")
    exits = qs.exists()
    if exits:
        # to make it unique
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    instance.slug = create_slug(instance)
    # do other stuffs here


pre_save.connect(pre_save_post_receiver, sender=Blog)

singlepageblog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from.models import Blog, Tag

# Create your views here.


def index(request):
    blog_list = Blog.objects.all()
    tag_list = Tag.objects.all()
    context = {
        # to dispaly in front-end, we first make list and then context by adding like story_list and tag_list
        "blog_list": blog_list,
        "tag_list": tag_list
    }
    return render(request, 'blog/blog.html', context)


def blog_detail(request):
    # Blog is model and slug is used for query.
    instance = get_object_or_404(Blog, slug=slug)
    context = {
        "instance": instance
    }
    return render(request, 'blog/blogDetails.html', context)


def blog_tag(request, name=None):
    blog_list = Blog.objects.filter(tag__name=name)
    tag_list = Tag.objects.all()
    context = {
        "blog_list": blog_list,
        "name": name,
        "tag_list": tag_list

    }
    return render(request, 'blog/tag-blog.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
    <!-- start nav -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">My Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'singlepageblog:index' %}">Features</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- end nav -->

    {% block content %}
    {% endblock content %}


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>

</body>

</html>

templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}
{% block meta_links %}
{% endblock %}
{% block style_links %}
{% endblock %}

{% block title %}
Blog
{% endblock %}

{% block content%}
<div class="container">
  <div class="row">
    <div class="col">
      <h3>My Stories</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-10">
      <div class="row">
        {% for blog in blog_list %}
        <div class="col-md-4">
          <div class="card blog-card">
            <img class="card-img-top" src="{{blog.image.url}}" alt="Card image cap">
            <div class="card-body">
              <h5 class="card-title">{{blog.title}}</h5>
              <p class="card-text">{{blog.content|striptags|truncatewords:30}}</p>
              <a href="{{blog.get_absolute_url}}" class="btn btn-primary">show detail</a>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-xs-12 col-md-2">
      <div class="row">
        <div class="col">
          <h4>Tags</h4>
        </div>
      </div>
      <div class="row">
        <div class="col">
          {% for tag in tag_list %}

          <p class="tag-name"><a href="{{tag.get_absolute_url}}">{{ tag.name }} </a></p>

          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock%}

{% block  script_link %}
{% endblock %}
{% block scripts %}
{% endblock %}

templates/blog/blogDetails.html
{% extends 'base.html' %}
{% load static %}

{% block meta_links %}
{% endblock %}
{% block style_links %}
{% endblock %}


{% block title %}
{{instance.title}}
{% endblock %}

{% block content%}
<div class="row">
    <div class="col">
        <div class="container">
            <h3>{{instance.title}}</h3>
            <img src="{{instance.image.url}}" alt="{{instance.title}}" class="img-fluid">
            <p class="text-muted">{{instance.date|date:"M"}},{{instance.date.day}},{{instance.date.year}}|{{instance.tag.name}} </p>
            <p class="mt-3">{{instance.content|safe}}</p>
        </div>
    </div>
</div>
{% endblock%}

{% block  script_link %}
{% endblock %}
{% block scripts %}
{% endblock %}

templates/blog/tag-blog.html
{% extends 'base.html' %}
{% load static %}

{% block meta_links %}
{% endblock %}
{% block style_links %}
{% endblock %}


{% block title %}
My Blog | {{name}}
{% endblock %}

{% block content%}
<div class="container">
    <div class="row">
        <div class="col">
            <h3>My Blogs</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-md-10">
            <div class="row">
                {% for blog in blog_list %}
                <div class="col-md-4">
                    <div class="card blog-card">
                        <img class=" card-img-top" src="{{blog.image.url}}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">{{blog.title}}</h5>
                            <p class="card-text">{{blog.content|striptags|truncatewords:30}}</p>
                            <a href="{{blog.get_absolute_url}}" class="btn btn-primary">show detail</a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-xs-12 col-md-2">
            <div class="row">
                <div class="col">
                    <h4>Tags</h4>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {% for tag in tag_list %}
                    <p class="tag-name"><a href="{{tag.get_absolute_url}}">{{ tag.name }} </a></p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock%}

{% block  script_link %}
{% endblock %}
{% block scripts %}
{% endblock %}